"""
RAMP Validation Engine

Overlays RAMP simulated stochastic profiles against real datalogger telemetry.
Calculates Tier 1 (Error) and Tier 2 (Structural) validation metrics.
Automatically detects the simulated file generated by Script 3.
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import argparse
from pathlib import Path
import sys
import random

# Define paths matching the project structure
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
INPUT_DIR_REAL = PROJECT_ROOT / "data" / "clean" / "timeseries"
INPUT_DIR_SIM = SCRIPT_DIR / "output"
OUTPUT_DIR = SCRIPT_DIR / "output"
FIGURES_DIR = OUTPUT_DIR / "figures"
METRICS_DIR = OUTPUT_DIR / "metrics"

# Ensure output directories exist
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
METRICS_DIR.mkdir(parents=True, exist_ok=True)

def load_and_prep_data(user_id, num_days=None, target_months=None):
    """Loads real data and automatically locates the simulated data for the user."""
    print(f"\n[*] Loading Real Data for User: {user_id}")
    
    # 1. Load Real Data
    real_file = INPUT_DIR_REAL / f"tpdin_user_{user_id}.csv"
    if not real_file.exists():
        real_file = INPUT_DIR_REAL / f"old_user_{user_id}.csv"
        if not real_file.exists():
            print(f"[-] Error: Real data file not found for User {user_id} in {INPUT_DIR_REAL}")
            sys.exit(1)
            
    df_real = pd.read_csv(real_file)
    df_real['timestamp'] = pd.to_datetime(df_real['corrected_timestamp'], errors='coerce')
    df_real = df_real.dropna(subset=['timestamp'])
    
    # Calculate total real power safely
    zero_series = pd.Series(0.0, index=df_real.index)
    v_usb = df_real.get('v_usb', zero_series)
    c_usb = df_real.get('c_usb', zero_series)
    v_led_1 = df_real.get('v_led_1', zero_series)
    c_led_1 = df_real.get('c_led_1', df_real.get('c_led', zero_series)) # Handles OLD format
    v_led_2 = df_real.get('v_led_2', zero_series)
    c_led_2 = df_real.get('c_led_2', zero_series)
    
    p_led_1 = (v_led_1 * c_led_1).clip(lower=0)
    p_led_2 = (v_led_2 * c_led_2).clip(lower=0)
    p_usb = (v_usb * c_usb).clip(lower=0)
    
    df_real['p_total'] = p_led_1 + p_led_2 + p_usb
    df_real['date_only'] = df_real['timestamp'].dt.date
    df_real['time_decimal'] = df_real['timestamp'].dt.hour + df_real['timestamp'].dt.minute / 60.0

    # 2. Auto-Detect Simulated Data
    sim_pattern = f"simulated_profile_user_{user_id}_*.csv"
    sim_files = list(INPUT_DIR_SIM.glob(sim_pattern))
    
    if not sim_files:
        print(f"[-] Error: Simulated data not found for User {user_id}")
        print(f"    Looked for: {INPUT_DIR_SIM}/{sim_pattern}")
        print("    Ensure you run '3_run_ramp_simulation.py' first.")
        sys.exit(1)
        
    # Get the most recently modified file and extract the profile name
    sim_files.sort(key=lambda x: x.stat().st_mtime, reverse=True)
    sim_file = sim_files[0]
    profile_name = sim_file.stem.replace(f"simulated_profile_user_{user_id}_", "").upper()
    
    print(f"[*] Found Simulated Data: {sim_file.name}")
    print(f"[*] Profile Detected: {profile_name}")
    
    df_sim = pd.read_csv(sim_file)
    df_sim['timestamp'] = pd.to_datetime(df_sim['DateTime'])
    df_sim['p_total'] = df_sim['Total Load [W]']
    df_sim['date_only'] = df_sim['timestamp'].dt.date
    df_sim['time_decimal'] = df_sim['timestamp'].dt.hour + df_sim['timestamp'].dt.minute / 60.0

    # 3. Apply Time Filters (Months or N Days)
    if target_months is not None:
        print(f"[*] Limiting validation strictly to Months: {target_months}...")
        df_real = df_real[df_real['timestamp'].dt.month.isin(target_months)]
        df_sim = df_sim[df_sim['timestamp'].dt.month.isin(target_months)]
        if df_real.empty or df_sim.empty:
            print(f"[-] Warning: Missing data for selected months.")
            
    elif num_days is not None and num_days > 0:
        print(f"[*] Limiting validation to first {num_days} days...")
        real_days = sorted(df_real['date_only'].unique())[:num_days]
        sim_days = sorted(df_sim['date_only'].unique())[:num_days]
        df_real = df_real[df_real['date_only'].isin(real_days)]
        df_sim = df_sim[df_sim['date_only'].isin(sim_days)]
        
    print(f"[+] Real data active: {df_real['date_only'].nunique()} days")
    print(f"[+] Sim data active:  {df_sim['date_only'].nunique()} days")

    if df_real.empty or df_sim.empty:
        print("[-] Cannot proceed: Datasets are empty after filtering.")
        sys.exit(1)

    # 4. Create standardized time bins (15-minute intervals) for smooth averaging
    bins = np.arange(0, 24.25, 0.25)
    df_real['time_bin'] = pd.cut(df_real['time_decimal'], bins, labels=bins[:-1])
    df_sim['time_bin'] = pd.cut(df_sim['time_decimal'], bins, labels=bins[:-1])

    return df_real, df_sim, profile_name


def plot_shadows_and_average(df_real, df_sim, user_id, profile_name):
    """Plot 1: Side-by-side plot of all daily curves (soft) overlaid with the mean curve (strong)."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6), sharey=True)
    
    # REAL DATA PLOT
    for date in df_real['date_only'].unique():
        day_data = df_real[df_real['date_only'] == date]
        ax1.plot(day_data['time_decimal'], day_data['p_total'], color='gray', alpha=0.08, linewidth=1)
        
    real_mean = df_real.groupby('time_bin', observed=True)['p_total'].mean()
    ax1.plot(real_mean.index.astype(float), real_mean.values, color='black', linewidth=3.5, label='Real Average Load')
    
    ax1.set_title(f'Real Measured Data (User {user_id})\nDaily Variance vs Average', fontsize=14, fontweight='bold')
    ax1.set_xlabel('Hour of the Day', fontsize=12)
    ax1.set_ylabel('Power Demand (W)', fontsize=12)
    ax1.set_xticks(np.arange(0, 25, 3))
    ax1.grid(True, linestyle='--', alpha=0.5)
    ax1.legend(loc='upper right', fontsize=11)
    ax1.set_ylim(bottom=0)

    # SIMULATED DATA PLOT
    for date in df_sim['date_only'].unique():
        day_data = df_sim[df_sim['date_only'] == date]
        ax2.plot(day_data['time_decimal'], day_data['p_total'], color='cornflowerblue', alpha=0.08, linewidth=1)
        
    sim_mean = df_sim.groupby('time_bin', observed=True)['p_total'].mean()
    ax2.plot(sim_mean.index.astype(float), sim_mean.values, color='darkblue', linewidth=3.5, label='Simulated Average Load')

    ax2.set_title(f'RAMP Simulation ({profile_name})\nDaily Variance vs Average', fontsize=14, fontweight='bold')
    ax2.set_xlabel('Hour of the Day', fontsize=12)
    ax2.set_xticks(np.arange(0, 25, 3))
    ax2.grid(True, linestyle='--', alpha=0.5)
    ax2.legend(loc='upper right', fontsize=11)

    plt.tight_layout()
    out_path = FIGURES_DIR / f"val_shadows_mean_U{user_id}_{profile_name.lower()}.png"
    plt.savefig(out_path, dpi=300)
    print(f"✓ Saved Shadow Plot: {out_path.name}")
    plt.close()


def plot_overlaid_averages(df_real, df_sim, user_id, profile_name):
    """Plot 2: Single plot overlaying both Measured and Simulated average curves for direct comparison."""
    plt.figure(figsize=(10, 6))
    
    # Calculate means
    real_mean = df_real.groupby('time_bin', observed=True)['p_total'].mean()
    sim_mean = df_sim.groupby('time_bin', observed=True)['p_total'].mean()
    
    # Plot Real
    plt.plot(real_mean.index.astype(float), real_mean.values, color='black', linewidth=3, label='Measured Average Load')
    
    # Plot Simulated
    plt.plot(sim_mean.index.astype(float), sim_mean.values, color='darkblue', linewidth=3, linestyle='--', label='Simulated Average Load')
    
    # Formatting
    plt.title(f'Overlay: Measured vs Simulated Average Load\nUser {user_id} | {profile_name}', fontsize=14, fontweight='bold')
    plt.xlabel('Hour of the Day', fontsize=12)
    plt.ylabel('Power Demand (W)', fontsize=12)
    plt.xticks(np.arange(0, 25, 3))
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend(loc='upper left', fontsize=12)
    plt.ylim(bottom=0)
    
    plt.tight_layout()
    out_path = FIGURES_DIR / f"val_overlay_mean_U{user_id}_{profile_name.lower()}.png"
    plt.savefig(out_path, dpi=300)
    print(f"✓ Saved Overlaid Average Plot: {out_path.name}")
    plt.close()


def plot_random_week(df_real, df_sim, user_id, profile_name):
    """Plot 3: Compare a continuous 7-day period to visualize intermittency and usage clusters."""
    real_dates = sorted(df_real['date_only'].unique())
    sim_dates = sorted(df_sim['date_only'].unique())
    
    if len(real_dates) < 7 or len(sim_dates) < 7:
        print("[-] Not enough days to plot a full week. Skipping weekly plot.")
        return

    r_start_idx = random.randint(0, len(real_dates) - 8)
    s_start_idx = random.randint(0, len(sim_dates) - 8)
    
    real_week_df = df_real[df_real['date_only'].isin(real_dates[r_start_idx : r_start_idx + 7])].copy()
    sim_week_df = df_sim[df_sim['date_only'].isin(sim_dates[s_start_idx : s_start_idx + 7])].copy()

    real_week_df['hour_continuous'] = (real_week_df['timestamp'] - real_week_df['timestamp'].min()).dt.total_seconds() / 3600.0
    sim_week_df['hour_continuous'] = (sim_week_df['timestamp'] - sim_week_df['timestamp'].min()).dt.total_seconds() / 3600.0

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 8), sharex=True, sharey=True)
    
    ax1.plot(real_week_df['hour_continuous'], real_week_df['p_total'], color='black', linewidth=1.5)
    ax1.set_title(f'Real Measured Load: Continuous Random Week (User {user_id})', fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.set_ylabel('Power (W)')

    ax2.plot(sim_week_df['hour_continuous'], sim_week_df['p_total'], color='blue', linewidth=1.5)
    ax2.set_title(f'RAMP Simulated Load: Continuous Random Week ({profile_name})', fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.set_xlabel('Hours (7 Days = 168 Hours)')
    ax2.set_ylabel('Power (W)')
    ax2.set_xticks(np.arange(0, 169, 24))

    plt.tight_layout()
    out_path = FIGURES_DIR / f"val_random_week_U{user_id}_{profile_name.lower()}.png"
    plt.savefig(out_path, dpi=300)
    print(f"✓ Saved Week Plot: {out_path.name}")
    plt.close()


def calculate_structural_metrics(df):
    """Extracts Tier 2 structural profiling metrics, returning Means and Standard Deviations."""
    daily_peak_idx = df.groupby('date_only')['p_total'].idxmax()
    peak_hours_series = df.loc[daily_peak_idx.dropna(), 'timestamp'].dt.hour
    modal_peak_hour = int(peak_hours_series.mode()[0]) if not peak_hours_series.empty else 0
    
    night_data = df[(df['timestamp'].dt.hour >= 0) & (df['timestamp'].dt.hour < 4)]
    daily_night_mean = night_data.groupby('date_only')['p_total'].mean()
    base_load_mean = daily_night_mean.mean() if not daily_night_mean.empty else 0.0
    base_load_std = daily_night_mean.std() if not daily_night_mean.empty else 0.0
    
    interval_hours = df['timestamp'].diff().median().total_seconds() / 3600.0
    if pd.isna(interval_hours) or interval_hours == 0:
        interval_hours = 5.0 / 60.0  
        
    daily_energy_Wh = df.groupby('date_only')['p_total'].sum() * interval_hours
    wh_mean = daily_energy_Wh.mean()
    wh_std = daily_energy_Wh.std()
    mrsd = (wh_std / wh_mean) if wh_mean > 0 else 0.0

    daily_mean_power = df.groupby('date_only')['p_total'].mean()
    overall_mean = daily_mean_power.mean() if not daily_mean_power.empty else 0.0
    overall_std = daily_mean_power.std() if not daily_mean_power.empty else 0.0
    
    time_periods = {'morning': (4, 10), 'daytime': (10, 17), 'evening': (17, 24), 'night': (0, 4)}
    rmp_metrics = {}
    for name, (start_h, end_h) in time_periods.items():
        p_data = df[(df['timestamp'].dt.hour >= start_h) & (df['timestamp'].dt.hour < end_h)]
        daily_period_mean = p_data.groupby('date_only')['p_total'].mean()
        rmp_metrics[f'{name}_mean'] = daily_period_mean.mean() if not daily_period_mean.empty else 0.0
        rmp_metrics[f'{name}_std'] = daily_period_mean.std() if not daily_period_mean.empty else 0.0

    return {
        'modal_peak': modal_peak_hour,
        'base_mean': base_load_mean, 'base_std': base_load_std,
        'mrsd': mrsd, 'wh_mean': wh_mean, 'wh_std': wh_std,
        'overall_p_mean': overall_mean, 'overall_p_std': overall_std,
        'rmp': rmp_metrics
    }


def calculate_validation_metrics(df_real, df_sim, user_id, profile_name, epsilon_watts=0.5):
    """Calculates Dual-Tier validation metrics and formats them into a DataFrame."""
    print("\n[*] Calculating Dual-Tier validation metrics...")
    
    # TIER 1: TIME-SERIES ALIGNMENT (Using the daily average profile)
    real_profile = df_real.groupby('time_bin', observed=True)['p_total'].mean().fillna(0).values
    sim_profile = df_sim.groupby('time_bin', observed=True)['p_total'].mean().fillna(0).values

    # Calculate absolute peaks and curve peaks safely
    real_avg_peak = np.max(real_profile) if len(real_profile) > 0 else 0.0
    sim_avg_peak = np.max(sim_profile) if len(sim_profile) > 0 else 0.0
    real_abs_peak = df_real['p_total'].max()
    sim_abs_peak = df_sim['p_total'].max()

    rmse = np.sqrt(np.mean((real_profile - sim_profile) ** 2))
    mpdada = abs(np.max(sim_profile) - np.max(real_profile)) / np.mean(real_profile) if np.mean(real_profile) > 0 else 0

    n, m = len(real_profile), len(sim_profile)
    dp = np.zeros((n + 1, m + 1))
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            if abs(real_profile[i-1] - sim_profile[j-1]) <= epsilon_watts:
                dp[i][j] = dp[i-1][j-1] + 1
            else:
                dp[i][j] = max(dp[i-1][j], dp[i][j-1])
    lcss_score = dp[n][m] / max(n, m)

    # TIER 2: STRUCTURAL PROFILING
    r_metrics = calculate_structural_metrics(df_real)
    s_metrics = calculate_structural_metrics(df_sim)

    # Helper function to compute and format absolute + relative error securely
    def fmt_err(real_val, sim_val, unit="W"):
        abs_err = abs(real_val - sim_val)
        rel_err = (abs_err / real_val * 100) if real_val > 0 else 0.0
        return f"{abs_err:.2f} {unit} ({rel_err:.1f}%)"

    metrics_list = [
        {"Metric Group": "Tier 1: Error", "Metric": "RMSE (Watts)", "Real (Mean ± Std)": "—", "Sim (Mean ± Std)": f"{rmse:.3f}", "Mean Abs Error": "—"},
        {"Metric Group": "Tier 1: Error", "Metric": "LCSS Score", "Real (Mean ± Std)": "—", "Sim (Mean ± Std)": f"{lcss_score:.3f}", "Mean Abs Error": "—"},
        {"Metric Group": "Tier 1: Error", "Metric": "MPDADA Ratio", "Real (Mean ± Std)": "—", "Sim (Mean ± Std)": f"{mpdada:.3f}", "Mean Abs Error": "—"},
        
        {"Metric Group": "Tier 2: Structure", "Metric": "Modal Peak Hour", 
         "Real (Mean ± Std)": f"{r_metrics['modal_peak']:02d}:00", 
         "Sim (Mean ± Std)": f"{s_metrics['modal_peak']:02d}:00", 
         "Mean Abs Error": f"{abs(r_metrics['modal_peak'] - s_metrics['modal_peak'])} hrs"},

        {"Metric Group": "Tier 2: Structure", "Metric": "Average Curve Peak (W)", 
         "Real (Mean ± Std)": f"{real_avg_peak:.2f}", 
         "Sim (Mean ± Std)": f"{sim_avg_peak:.2f}", 
         "Mean Abs Error": fmt_err(real_avg_peak, sim_avg_peak, "W")},

        {"Metric Group": "Tier 2: Structure", "Metric": "Absolute Max Power (W)", 
         "Real (Mean ± Std)": f"{real_abs_peak:.2f}", 
         "Sim (Mean ± Std)": f"{sim_abs_peak:.2f}", 
         "Mean Abs Error": fmt_err(real_abs_peak, sim_abs_peak, "W")},
         
        {"Metric Group": "Tier 2: Structure", "Metric": "MRSD (Chaos Index)", 
         "Real (Mean ± Std)": f"{r_metrics['mrsd']:.3f}", 
         "Sim (Mean ± Std)": f"{s_metrics['mrsd']:.3f}", 
         "Mean Abs Error": f"{abs(r_metrics['mrsd'] - s_metrics['mrsd']):.3f} ({abs(r_metrics['mrsd'] - s_metrics['mrsd'])/r_metrics['mrsd']*100:.1f}%)"},

        {"Metric Group": "Tier 2: Energy & Variance", "Metric": "Overall Mean Power (W)", 
         "Real (Mean ± Std)": f"{r_metrics['overall_p_mean']:.2f} ± {r_metrics['overall_p_std']:.2f}", 
         "Sim (Mean ± Std)": f"{s_metrics['overall_p_mean']:.2f} ± {s_metrics['overall_p_std']:.2f}", 
         "Mean Abs Error": fmt_err(r_metrics['overall_p_mean'], s_metrics['overall_p_mean'], "W")},

        {"Metric Group": "Tier 2: Energy & Variance", "Metric": "Daily Energy (Wh)", 
         "Real (Mean ± Std)": f"{r_metrics['wh_mean']:.2f} ± {r_metrics['wh_std']:.2f}", 
         "Sim (Mean ± Std)": f"{s_metrics['wh_mean']:.2f} ± {s_metrics['wh_std']:.2f}", 
         "Mean Abs Error": fmt_err(r_metrics['wh_mean'], s_metrics['wh_mean'], "Wh")},
         
        {"Metric Group": "Tier 2: Energy & Variance", "Metric": "Base Load (W) [00:00-04:00]", 
         "Real (Mean ± Std)": f"{r_metrics['base_mean']:.2f} ± {r_metrics['base_std']:.2f}", 
         "Sim (Mean ± Std)": f"{s_metrics['base_mean']:.2f} ± {s_metrics['base_std']:.2f}", 
         "Mean Abs Error": fmt_err(r_metrics['base_mean'], s_metrics['base_mean'], "W")},

        {"Metric Group": "Tier 2: Macro Windows", "Metric": "Morning Load (W) [04:00-10:00]", 
         "Real (Mean ± Std)": f"{r_metrics['rmp']['morning_mean']:.2f} ± {r_metrics['rmp']['morning_std']:.2f}", 
         "Sim (Mean ± Std)": f"{s_metrics['rmp']['morning_mean']:.2f} ± {s_metrics['rmp']['morning_std']:.2f}", 
         "Mean Abs Error": fmt_err(r_metrics['rmp']['morning_mean'], s_metrics['rmp']['morning_mean'], "W")},
         
        {"Metric Group": "Tier 2: Macro Windows", "Metric": "Daytime Load (W) [10:00-17:00]", 
         "Real (Mean ± Std)": f"{r_metrics['rmp']['daytime_mean']:.2f} ± {r_metrics['rmp']['daytime_std']:.2f}", 
         "Sim (Mean ± Std)": f"{s_metrics['rmp']['daytime_mean']:.2f} ± {s_metrics['rmp']['daytime_std']:.2f}", 
         "Mean Abs Error": fmt_err(r_metrics['rmp']['daytime_mean'], s_metrics['rmp']['daytime_mean'], "W")},
         
        {"Metric Group": "Tier 2: Macro Windows", "Metric": "Evening Peak (W) [17:00-24:00]", 
         "Real (Mean ± Std)": f"{r_metrics['rmp']['evening_mean']:.2f} ± {r_metrics['rmp']['evening_std']:.2f}", 
         "Sim (Mean ± Std)": f"{s_metrics['rmp']['evening_mean']:.2f} ± {s_metrics['rmp']['evening_std']:.2f}", 
         "Mean Abs Error": fmt_err(r_metrics['rmp']['evening_mean'], s_metrics['rmp']['evening_mean'], "W")},
         
        {"Metric Group": "Tier 2: Macro Windows", "Metric": "Night Load (W) [00:00-04:00]", 
         "Real (Mean ± Std)": f"{r_metrics['rmp']['night_mean']:.2f} ± {r_metrics['rmp']['night_std']:.2f}", 
         "Sim (Mean ± Std)": f"{s_metrics['rmp']['night_mean']:.2f} ± {s_metrics['rmp']['night_std']:.2f}", 
         "Mean Abs Error": fmt_err(r_metrics['rmp']['night_mean'], s_metrics['rmp']['night_mean'], "W")}
    ]
    
    df_results = pd.DataFrame(metrics_list)
    metrics_file = METRICS_DIR / f"validation_U{user_id}_{profile_name.lower()}.csv"
    df_results.to_csv(metrics_file, index=False)
    
    print("\n" + "="*105)
    print(f" VALIDATION RESULTS: User {user_id} vs {profile_name}")
    print("="*105)
    print(df_results[['Metric', 'Real (Mean ± Std)', 'Sim (Mean ± Std)', 'Mean Abs Error']].to_string(index=False))
    print("="*105 + "\n")
    print(f"✓ Saved Metrics Table: {metrics_file.name}")
    
    return df_results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Validate Simulated Scenarios against Real User Data")
    parser.add_argument("--user", type=str, required=True, help="Real User ID for baseline (e.g., '74')")
    parser.add_argument("--days", type=int, default=None, help="Limit validation to first N days")
    parser.add_argument("--months", type=int, nargs='+', choices=range(1, 13), default=None, 
                        help="Limit validation to specific months (e.g., --months 1 2 3)")
                        
    args = parser.parse_args()
    
    df_real, df_sim, profile_name = load_and_prep_data(args.user, num_days=args.days, target_months=args.months)
    
    plot_shadows_and_average(df_real, df_sim, args.user, profile_name)
    plot_overlaid_averages(df_real, df_sim, args.user, profile_name) 
    plot_random_week(df_real, df_sim, args.user, profile_name)
    calculate_validation_metrics(df_real, df_sim, args.user, profile_name)
    
    print("[+] Validation Complete!")